In [2]:
import numpy as np

In [3]:
my_arr=np.arrange(1000000)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
my_arr = np.arange(1000000)

In [ ]:
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2

In [ ]:
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

In [ ]:
# 可以看出，Python中numpy自带的全量数组使用更加方便。代码量少、占用内存少而且时间更快

In [ ]:
# 生成随机数组
data = np.random.randn(2,3)

In [ ]:
data

In [ ]:
# data简单的数学操作，与数学上矩阵的应用相同
data * 10

In [ ]:
data+data

In [ ]:
data+=1

In [ ]:
data

In [ ]:
data.shape

In [ ]:
data.dtype

In [ ]:
my_arr

In [ ]:
# 4.1 生成ndarray

In [ ]:
data1 = [1,2,3,4,5,6]
arr1 = np.array(data1)

In [ ]:
arr1

In [ ]:
# 嵌套长度则自动转化为同等长度的数组
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)

In [ ]:
arr2

In [ ]:
# 测试——如果长度不相等会发生什么
data3 = [[1,2,3],[4,5]]
arr3 = np.array(data3)

In [ ]:
arr3

In [ ]:
# 也有很多已知函数可以创建特殊的数组
np.zeros(10)

In [ ]:
np.ones(20)

In [ ]:
np.ones((3,4))

In [ ]:
np.empty((2,7))

# NUMPY数据类型
## 数据类型——元数据，为某一类型声明的内存块信息

## 可以使用astype方法进行显性转换，生成新的数组（哪怕传递参数是一样的）

In [12]:
arr = np.array([1,2,3,4,5])


In [13]:
arr.dtype

dtype('int32')

## 这个数据类型是被自动分配的大小，后续也可以使用astype转化为想要的

In [14]:
float_arr = arr.astype(np.float64)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
float

float

In [18]:
float_arr

array([1., 2., 3., 4., 5.])

## 数据类型np.float64也可以直接写成float——numpy允许这样的参数

# NUMPY数组算术

## 允许批量运算不需要for循环——向量化
## 任何两个等尺寸数组之间的算术操作都应用了逐元素操作的方法，和数字之间的运算没有区别，相当于对每一个元素或对应元素进行了相关操作

In [20]:
arr = np.array({1,2,3},[4,5,6])

TypeError: data type not understood

In [21]:
# 传入类型应该是列表之类的形式
arr = np.array([[1,2,3],[4,5,6]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr?

In [24]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [25]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [26]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

# 基础索引与切片

## 一维数组简单，看起来和Python区别不大

In [27]:
arr = np.arange(10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]

5

In [30]:
arr[1:45]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr{::-1}

SyntaxError: invalid syntax (<ipython-input-31-60e85403d49d>, line 1)

In [32]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
arr_neg = arr[8:5:-1]

In [37]:
arr_neg

array([8, 7, 6])

## 需要注意这里面任何一个切片都是原数组的一个视图——其修改会相互影响